"""Repository: CategoryRepository."""

from __future__ import annotations

from sqlalchemy import select

from app.models.category import Category
from app.repositories.base import BaseRepository
from app.utils.errors import ConflictError

CategoryNameIndex = dict[str, list[Category]]


def category_name_key(name: str) -> str:
    """Shared key normalization; preserves accents and internal whitespace in saved names."""
    return name.strip().casefold()


class CategoryRepository(BaseRepository[Category]):
    model = Category

    def build_name_index(self) -> CategoryNameIndex:
        """Operation-local snapshot, never a cache shared between requests."""
        index: CategoryNameIndex = {}
        for category in self.list():
            index.setdefault(category_name_key(category.name), []).append(category)
        return index

    def get_by_name(self, name: str, *, index: CategoryNameIndex | None = None) -> Category | None:
        if index is None:
            index = self.build_name_index()
        matches = index.get(category_name_key(name), [])
        if len(matches) > 1:
            ids = sorted(category.id for category in matches)
            raise ConflictError(
                f"Category '{name}' is ambiguous: it matches IDs {', '.join(map(str, ids))}",
                detail={"name": name, "category_ids": ids},
            )
        return matches[0] if matches else None

    def get_by_name_ci(
        self, name: str, *, index: CategoryNameIndex | None = None
    ) -> Category | None:
        return self.get_by_name(name, index=index)

    def get_or_create(self, name: str, type_: str) -> Category:
        """Find a system category case-insensitively or create it for cash movements generated by
        transfers, trades, and income. If a user deletes it, the next relevant operation
        recreates it to keep generated movements categorized.
        """
        existing = self.get_by_name_ci(name)
        if existing is not None:
            if existing.type != type_ or self.has_children(existing.id):
                raise ConflictError(
                    f"Automatic category '{existing.name}' must be a leaf " f"of type '{type_}'",
                    detail={
                        "category_id": existing.id,
                        "category_type": existing.type,
                        "expected_type": type_,
                    },
                )
            return existing
        return self.add(Category(name=name, type=type_, is_system=True, parent_id=None))

    def has_children(self, category_id: int) -> bool:
        return (
            self.db.scalar(select(Category.id).where(Category.parent_id == category_id).limit(1))
            is not None
        )

    def list(self) -> list[Category]:
        return list(self.db.scalars(select(Category).order_by(Category.name)))
