"""Repository: TransactionRepository."""

from __future__ import annotations

import datetime as dt
from collections.abc import Iterator

from sqlalchemy import func, select

from app.models.account import Account
from app.models.category import Category
from app.models.transaction import Transaction
from app.repositories.base import BaseRepository


class TransactionRepository(BaseRepository[Transaction]):
    model = Transaction

    def get_by_hash(self, import_hash: str) -> Transaction | None:
        return self.db.scalars(
            select(Transaction).where(Transaction.import_hash == import_hash)
        ).first()

    def get_transfer_sibling(self, transfer_group_id: str, exclude_id: int) -> Transaction | None:
        return self.db.scalars(
            select(Transaction).where(
                Transaction.transfer_group_id == transfer_group_id,
                Transaction.id != exclude_id,
            )
        ).first()

    def get_by_link(self, link_field: str, link_id: int) -> Transaction | None:
        """Find the cash movement generated by a trade, income payment, or recurring cost through
        its link column. Allowed column names are validated by
        app.services.linked_transaction.LINK_FIELDS before reaching this parameterized query.
        """
        return self.db.scalars(
            select(Transaction).where(getattr(Transaction, link_field) == link_id)
        ).first()

    SORTABLE_COLUMNS = {
        "date": Transaction.date,
        "amount": Transaction.amount_eur,
        "description": func.coalesce(Transaction.description, "").collate("PFIM_NATURAL_NOCASE"),
    }

    @staticmethod
    def _filters(
        *,
        account_id: int | None = None,
        category_id: int | None = None,
        date_from: dt.date | None = None,
        date_to: dt.date | None = None,
    ) -> list:
        filters = []
        if account_id is not None:
            filters.append(Transaction.account_id == account_id)
        if category_id is not None:
            filters.append(Transaction.category_id == category_id)
        if date_from is not None:
            filters.append(Transaction.date >= date_from)
        if date_to is not None:
            filters.append(Transaction.date <= date_to)
        return filters

    def list(
        self,
        *,
        account_id: int | None = None,
        category_id: int | None = None,
        date_from: dt.date | None = None,
        date_to: dt.date | None = None,
        page: int = 1,
        page_size: int = 50,
        sort_by: str = "date",
        sort_dir: str = "desc",
    ) -> tuple[list[Transaction], int]:
        filters = self._filters(
            account_id=account_id,
            category_id=category_id,
            date_from=date_from,
            date_to=date_to,
        )

        count_stmt = select(func.count()).select_from(Transaction)
        for f in filters:
            count_stmt = count_stmt.where(f)
        total = self.db.scalar(count_stmt) or 0

        stmt = select(Transaction)
        if sort_by == "account_id":
            stmt = stmt.join(Account, Account.id == Transaction.account_id)
            sort_column = func.coalesce(Account.name, "").collate("PFIM_NATURAL_NOCASE")
        elif sort_by == "category_id":
            stmt = stmt.join(Category, Category.id == Transaction.category_id)
            sort_column = func.coalesce(Category.name, "").collate("PFIM_NATURAL_NOCASE")
        else:
            sort_column = self.SORTABLE_COLUMNS.get(sort_by, Transaction.date)
        order = sort_column.asc() if sort_dir == "asc" else sort_column.desc()

        for f in filters:
            stmt = stmt.where(f)
        order_prefix = []
        if sort_by == "description":
            # As in client-sorted tables, null or empty values stay last in both directions. This
            # expression is False (0) for present text and True (1) for missing text.
            #
            description_missing = func.coalesce(func.trim(Transaction.description), "") == ""
            order_prefix.append(description_missing.asc())
        stmt = stmt.order_by(*order_prefix, order, Transaction.id.desc())
        stmt = stmt.offset((page - 1) * page_size).limit(page_size)
        items = list(self.db.scalars(stmt))
        return items, total

    def iter_filtered(
        self,
        *,
        account_id: int | None = None,
        category_id: int | None = None,
        date_from: dt.date | None = None,
        date_to: dt.date | None = None,
        batch_size: int = 2_000,
    ) -> Iterator[Transaction]:
        """Iterate all matching transactions without a silent cap. ID keyset pagination limits
        memory and avoids shifting offsets. Reports and internal aggregates use this path;
        list endpoints retain explicit pagination through list().
        """

        if batch_size <= 0:
            raise ValueError("batch_size must be greater than zero")
        filters = self._filters(
            account_id=account_id,
            category_id=category_id,
            date_from=date_from,
            date_to=date_to,
        )
        last_id = 0
        while True:
            stmt = select(Transaction).where(Transaction.id > last_id)
            for condition in filters:
                stmt = stmt.where(condition)
            batch = list(self.db.scalars(stmt.order_by(Transaction.id.asc()).limit(batch_size)))
            if not batch:
                return
            yield from batch
            last_id = batch[-1].id
