import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiFetch } from "./client";

export interface TaxSetting {
  key: string;
  value: string;
  description: string | null;
}

export function useTaxSettings() {
  return useQuery({
    queryKey: ["tax-settings"],
    queryFn: () => apiFetch<TaxSetting[]>("/tax-settings"),
  });
}

export function useUpdateTaxSetting() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ key, value }: { key: string; value: number }) =>
      apiFetch<TaxSetting>(`/tax-settings/${key}`, { method: "PUT", body: JSON.stringify({ value }) }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["tax-settings"] });
      // Tax rates feed report estimates; refresh reports after changes
      // so they do not continue displaying the previous estimated amounts.
      qc.invalidateQueries({ queryKey: ["reports"] });
    },
  });
}

/** Flexible tax register (specification §11.1).
 * Users can add any tax entry alongside events generated by sales:
 * external withholding, carried-forward losses or separately paid tax. */
export const TAX_EVENT_TYPES = [
  { value: "capital_gain", label: "Capital gain" },
  { value: "capital_loss", label: "Capital loss" },
  { value: "withholding", label: "Withholding tax" },
  { value: "substitute_tax", label: "Substitute tax" },
  { value: "other", label: "Other" },
] as const;

export function taxEventTypeLabel(type: string): string {
  return TAX_EVENT_TYPES.find((t) => t.value === type)?.label ?? type;
}

export interface TaxEvent {
  id: number;
  origin: "manual" | "automatic_trade" | "legacy_unknown";
  event_date: string;
  event_type: string;
  related_trade_id: number | null;
  related_income_id: number | null;
  description: string;
  gross_amount: string | null;
  tax_rate: string | null;
  tax_amount: string | null;
  net_amount: string | null;
  is_compensated: boolean;
  notes: string | null;
}

export interface TaxEventPayload {
  event_date: string;
  event_type: string;
  description: string;
  gross_amount?: string | null;
  tax_rate?: string | null;
  tax_amount?: string | null;
  notes?: string | null;
}

export interface TaxEventUpdatePayload extends Partial<TaxEventPayload> {
  related_trade_id?: number | null;
  related_income_id?: number | null;
  net_amount?: string | null;
  is_compensated?: boolean;
}

/** Tax entries affect both the register and related report estimates. */
function invalidateTaxRelated(qc: ReturnType<typeof useQueryClient>) {
  qc.invalidateQueries({ queryKey: ["tax-events"] });
  qc.invalidateQueries({ queryKey: ["reports"] });
}

export function useTaxEvents(range: { from?: string; to?: string } = {}) {
  const params = new URLSearchParams();
  if (range.from) params.set("date_from", range.from);
  if (range.to) params.set("date_to", range.to);
  const qs = params.toString();
  return useQuery({
    queryKey: ["tax-events", range.from ?? null, range.to ?? null],
    queryFn: () => apiFetch<TaxEvent[]>(`/tax-events${qs ? `?${qs}` : ""}`),
  });
}

export function useCreateTaxEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: TaxEventPayload) =>
      apiFetch<TaxEvent>("/tax-events", { method: "POST", body: JSON.stringify(data) }),
    onSuccess: () => invalidateTaxRelated(qc),
  });
}

export function useUpdateTaxEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: TaxEventUpdatePayload }) =>
      apiFetch<TaxEvent>(`/tax-events/${id}`, { method: "PUT", body: JSON.stringify(data) }),
    onSuccess: () => invalidateTaxRelated(qc),
  });
}

export function useDeleteTaxEvent() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: number) => apiFetch<void>(`/tax-events/${id}`, { method: "DELETE" }),
    onSuccess: () => invalidateTaxRelated(qc),
  });
}
