/** Shared frontend types aligned with backend Pydantic schemas.
 * apiFetch converts raw error responses into Error objects with an
 * extracted message, so callers do not need an error response type. */
import type { SecurityType } from "@/lib/securityTypes";
import type { PortfolioValuationMetadata } from "@/api/reports";

export interface Account {
  id: number;
  name: string;
  type: "checking" | "savings" | "investment" | "cash";
  currency: string;
  opening_balance: string;
  notes: string | null;
  is_active: boolean;
  reference_account_id: number | null;
  /** Null for legacy data whose original date cannot be reconstructed. */
  opened_on?: string | null;
  /** Server-managed: set when the account is deactivated. */
  closed_on?: string | null;
}

export interface Category {
  id: number;
  name: string;
  type: "income" | "expense" | "transfer";
  parent_id: number | null;
  color: string | null;
  icon: string | null;
  is_system: boolean;
}

export interface Transaction {
  id: number;
  account_id: number;
  /** Required for all new writes; nullable on reads to display legacy
   * rows created before the mandatory-category migration. */
  category_id: number | null;
  date: string;
  /** Amount in the declared currency. Always use amount_eur for totals. */
  amount: string;
  currency: string;
  /** Never null: conversion occurs at entry time. */
  fx_rate: string;
  amount_eur: string;
  description: string | null;
  notes: string | null;
  tags: string[];
  transfer_group_id: string | null;
  trade_id: number | null;
  income_event_id: number | null;
  /** Present on transactions generated by recurring costs. Like rows
   * with trade_id or income_event_id, these cannot be edited in Cash Flow. */
  portfolio_cost_id: number | null;
  created_at: string;
  updated_at: string | null;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
}

export interface Security {
  id: number;
  ticker: string;
  name: string;
  type: SecurityType;
  market: string | null;
  currency: string;
  isin: string | null;
  sector: string | null;
  industry: string | null;
  country: string | null;
  is_active: boolean;
}

export interface PositionLot {
  trade_id: number;
  date: string;
  quantity_remaining: string;
  unit_cost: string;
}

/** Open position in native currency and euros.
 * Display native values and sum euro values. Fields without a suffix
 * use the security's quoted currency, as on the broker statement.
 * Fields ending in _eur contain converted values frozen at entry time
 * and can be summed across different securities. */
export interface Position {
  security_id: number;
  ticker: string;
  name: string;
  quantity: string;
  currency: string;

  average_cost: string;
  total_invested: string;
  current_price: string | null;
  current_value: string | null;
  unrealized_gain_loss: string | null;
  /** Price-only performance, excluding exchange-rate effects. */
  unrealized_gain_loss_pct: string | null;

  average_cost_eur: string;
  total_invested_eur: string;
  current_price_eur: string | null;
  current_value_eur: string | null;
  unrealized_gain_loss_eur: string | null;
  /** Return in euros, including exchange-rate effects. */
  unrealized_gain_loss_pct_eur: string | null;
  /** Always in euros: included in the tax register. */
  realized_gain_loss: string;

  current_price_date: string | null;
  valuation_source: "market_price" | "fifo_cost";
  lots: PositionLot[];
}

export interface CsvImportProfile {
  id: number;
  name: string;
  delimiter: string;
  skip_rows: number;
  date_format: string;
  date_column: string;
  description_column: string;
  amount_column: string;
  category_column: string | null;
  decimal_separator: string;
  default_currency: string;
  created_at: string;
  updated_at: string | null;
}

export interface TradeCost {
  id: number;
  trade_id: number;
  cost_type: string;
  description: string | null;
  amount: string;
  currency: string;
  fx_rate: string;
  amount_eur: string;
  percentage_used: string | null;
  notes: string | null;
}

export interface Trade {
  id: number;
  security_id: number;
  account_id: number;
  type: "buy" | "sell";
  date: string;
  quantity: string;
  /** Unit price in the settlement currency (currency). */
  price: string;
  /** Unit price in the security's quoted currency. */
  quote_price: string;
  /** Settlement currency; may differ from the security's quoted currency. */
  currency: string;
  /** Never null: conversion occurs at entry time. */
  fx_rate: string;
  price_eur: string;
  total_amount: string;
  total_eur: string;
  notes: string | null;
  total_costs_eur: string;
  created_at: string;
  updated_at: string | null;
}

export interface IncomeEvent {
  id: number;
  security_id: number;
  account_id: number;
  event_type: "dividend" | "coupon" | "return_of_capital";
  ex_date: string | null;
  payment_date: string;
  quantity_held: string | null;
  amount_per_unit: string | null;
  total_amount: string;
  currency: string;
  /** Never null: conversion occurs at entry time. */
  fx_rate: string;
  total_eur: string;
  tax_withheld: string;
  /** Net after withholding: the amount credited to cash. */
  net_amount_eur: string;
  notes: string | null;
}

export interface IncomeEventsSummary {
  period_from: string | null;
  period_to: string | null;
  total_net_eur: string;
  by_security: { security_id: number; ticker: string; total_net_eur: string; events_count: number }[];
}

export interface PortfolioSummary {
  total_invested: string;
  total_current_value: string;
  total_unrealized_gain_loss: string;
  total_realized_gain_loss: string;
  positions_count: number;
  allocation_by_type: Record<string, string>;
  portfolio_valuation: PortfolioValuationMetadata;
}
