"""Verified SQLite backups published without copying the live file. Open the source read-only and
use the SQLite Online Backup API. A .partial copy becomes visible only after integrity,
foreign-key, Alembic revision and SHA-256 checks, plus a durable manifest. Restore delegates
to RestoreService for gating, operational locking, a preliminary backup and verifiable
recovery.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import re
import sqlite3
import uuid
from collections.abc import Callable
from contextlib import closing
from pathlib import Path
from time import monotonic
from typing import Any

from app.config import settings
from app.database import DATABASE_URL
from app.maintenance import durable_replace, operation_lock
from app.schemas.backup import BackupInfo, BackupStatus, RestoreRequest, RestoreResult
from app.utils.errors import NotFoundError, PFIMError, ValidationErrorPFIM

_BACKUP_FILENAME_PATTERN = re.compile(r"^pfim_backup_\d{8}_\d{6}(?:_\d{6}(?:_[0-9a-f]{8})?)?\.db$")
_NEW_BACKUP_FILENAME_PATTERN = re.compile(r"^pfim_backup_\d{8}_\d{6}_\d{6}_[0-9a-f]{8}\.db$")
_ORPHAN_FILENAME_PATTERN = re.compile(
    r"^\.pfim_backup_\d{8}_\d{6}_\d{6}_[0-9a-f]{8}"
    r"(?:\.db\.partial(?:-(?:wal|shm|journal))?|\.manifest\.json\.partial)$"
)
_FINAL_MANIFEST_PATTERN = re.compile(r"^pfim_backup_\d{8}_\d{6}_\d{6}_[0-9a-f]{8}\.manifest\.json$")
_MANIFEST_FORMAT_VERSION = 1
_ORPHAN_GRACE_PERIOD = dt.timedelta(hours=24)


class BackupUnavailableError(PFIMError):
    status_code = 503
    error_code = "BACKUP_UNAVAILABLE"


class BackupTimeoutError(BackupUnavailableError):
    error_code = "BACKUP_TIMEOUT"


class RestoreDisabledError(PFIMError):
    status_code = 503
    error_code = "RESTORE_DISABLED"


class BackupVerificationError(PFIMError):
    status_code = 500
    error_code = "BACKUP_VERIFICATION_FAILED"


class SchemaRevisionMismatchError(PFIMError):
    status_code = 409
    error_code = "SCHEMA_REVISION_MISMATCH"


def is_valid_backup_filename(filename: str) -> bool:
    """Accept only names generated by PFIM, including both legacy formats."""

    return bool(_BACKUP_FILENAME_PATTERN.fullmatch(filename))


def _get_db_path(database_url: str | None = None) -> Path:
    """Extract an on-disk SQLite path without creating or opening the database."""

    database_url = DATABASE_URL if database_url is None else database_url
    prefix = "sqlite:///"
    if not database_url.startswith(prefix):
        raise ValidationErrorPFIM(
            "Backups are supported only for file-based SQLite databases",
            detail={"database_url_scheme": database_url.split(":", maxsplit=1)[0]},
        )
    path_part = database_url[len(prefix) :]
    if not path_part or path_part == ":memory:" or path_part.startswith("file:"):
        raise ValidationErrorPFIM("Backups are supported only for file-based SQLite databases")
    return Path(path_part).resolve()


def _readonly_uri(path: Path) -> str:
    return f"{path.resolve().as_uri()}?mode=ro"


def _manifest_path(backup_path: Path) -> Path:
    return backup_path.with_suffix(".manifest.json")


def _sqlite_sidecars(path: Path) -> tuple[Path, ...]:
    return tuple(Path(f"{path}{suffix}") for suffix in ("-wal", "-shm", "-journal"))


def _present_sqlite_sidecars(path: Path) -> list[Path]:
    return [sidecar for sidecar in _sqlite_sidecars(path) if sidecar.exists()]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _fsync_file(path: Path) -> None:
    # Windows requires a writable descriptor for FlushFileBuffers. Using rb yields EBADF on
    # Python 3.14 even for an existing closed file. This is a staging/final file created by
    # PFIM, never the source database.
    with path.open("r+b") as stream:
        os.fsync(stream.fileno())


def _fsync_directory(path: Path) -> None:
    """Make renames durable where the runtime provides O_DIRECTORY, on POSIX."""

    directory_flag = getattr(os, "O_DIRECTORY", None)
    if directory_flag is None:
        return
    descriptor = os.open(path, os.O_RDONLY | directory_flag)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


class BackupService:
    def __init__(
        self,
        *,
        db_path: Path | None = None,
        backup_enabled: bool | None = None,
        expected_revision: str | None = None,
        progress: Callable[[int, int, int], None] | None = None,
    ) -> None:
        self.db_path = (db_path or _get_db_path()).resolve()
        self.data_dir = self.db_path.parent
        self.backup_enabled = settings.backup_enabled if backup_enabled is None else backup_enabled
        self.expected_revision = (
            settings.expected_alembic_revision if expected_revision is None else expected_revision
        ).strip()
        # Hook observable by concurrency tests; it neither determines backup correctness nor is
        # exposed by the router.
        self._progress = progress

    def status(self) -> BackupStatus:
        from app.services.restore_service import restore_runtime_status

        runtime = restore_runtime_status(self.data_dir)
        restore_configured = (
            bool(settings.restore_enabled) and self.backup_enabled and bool(self.expected_revision)
        )
        return BackupStatus(
            backup_enabled=self.backup_enabled and bool(self.expected_revision),
            restore_enabled=restore_configured and not bool(runtime["maintenance_mode"]),
            expected_alembic_revision=self.expected_revision,
            maintenance_mode=bool(runtime["maintenance_mode"]),
            restore_state=str(runtime["restore_state"]),
            active_restore_id=(
                str(runtime["active_restore_id"])
                if runtime["active_restore_id"] is not None
                else None
            ),
        )

    def _ensure_backup_enabled(self) -> None:
        if not self.backup_enabled:
            raise BackupUnavailableError(
                "Backup is disabled in the configuration",
                detail={"setting": "BACKUP_ENABLED"},
            )
        if not self.expected_revision:
            raise BackupUnavailableError(
                "Expected Alembic revision is not configured",
                detail={"setting": "EXPECTED_ALEMBIC_REVISION"},
            )

    def _restore_configuration_reason(self) -> str | None:
        if not self.backup_enabled:
            return "backup_disabled"
        if not self.expected_revision:
            return "expected_revision_missing"
        if not settings.restore_enabled:
            return "restore_disabled"
        return None

    def _new_paths(self) -> tuple[Path, Path, Path, Path]:
        timestamp = dt.datetime.now(dt.UTC).strftime("%Y%m%d_%H%M%S_%f")
        nonce = uuid.uuid4().hex[:8]
        filename = f"pfim_backup_{timestamp}_{nonce}.db"
        final_database = self.data_dir / filename
        final_manifest = _manifest_path(final_database)
        staging_database = self.data_dir / f".{filename}.partial"
        staging_manifest = self.data_dir / f".{final_manifest.name}.partial"
        return final_database, final_manifest, staging_database, staging_manifest

    def _online_copy(self, destination_path: Path) -> None:
        timeout_seconds = min(settings.sqlite_busy_timeout_ms / 1000, 0.1)
        copy_timeout = settings.backup_copy_timeout_seconds
        deadline = monotonic() + copy_timeout

        def check_deadline() -> None:
            if monotonic() >= deadline:
                raise BackupTimeoutError(
                    "Copy timeout exceeded: backup was not created",
                    detail={"timeout_seconds": copy_timeout, "retryable": True},
                )

        def progress(status: int, remaining: int, total: int) -> None:
            # The callback also runs on BUSY/LOCKED retries. Abandoning the HTTP request while leaving
            # the copy active is insufficient.
            check_deadline()
            if self._progress is not None:
                self._progress(status, remaining, total)
            check_deadline()

        try:
            with closing(
                sqlite3.connect(
                    _readonly_uri(self.db_path),
                    uri=True,
                    timeout=timeout_seconds,
                )
            ) as source, closing(
                sqlite3.connect(destination_path, timeout=timeout_seconds)
            ) as destination:
                check_deadline()
                source.backup(
                    destination,
                    pages=256,
                    progress=progress,
                    sleep=0.05,
                )
                check_deadline()
                checkpoint = destination.execute("PRAGMA wal_checkpoint(TRUNCATE)").fetchone()
                if checkpoint is not None and int(checkpoint[0]) != 0:
                    raise BackupVerificationError(
                        "Backup WAL checkpoint failed",
                        detail={"checkpoint": list(checkpoint)},
                    )
                journal_mode = destination.execute("PRAGMA journal_mode=DELETE").fetchone()
                if journal_mode is None or str(journal_mode[0]).lower() != "delete":
                    raise BackupVerificationError("Cannot make the SQLite backup self-contained")
                destination.commit()
        except BackupVerificationError:
            raise
        except (OSError, sqlite3.Error) as exc:
            error_code = getattr(exc, "sqlite_errorcode", None)
            primary_code = error_code & 0xFF if isinstance(error_code, int) else None
            if primary_code in {sqlite3.SQLITE_BUSY, sqlite3.SQLITE_LOCKED}:
                raise BackupUnavailableError(
                    "Database temporarily busy: backup was not created",
                    detail={"retryable": True},
                ) from exc
            raise BackupVerificationError("SQLite could not create the backup") from exc
        sidecars = _present_sqlite_sidecars(destination_path)
        if sidecars:
            raise BackupVerificationError(
                "The SQLite backup left sidecars that cannot be published",
                detail={"sidecars": [path.name for path in sidecars]},
            )

    def _validate_staging(self, staging_path: Path) -> str:
        try:
            sidecars = _present_sqlite_sidecars(staging_path)
            if sidecars:
                raise BackupVerificationError(
                    "Backup staging is not a self-contained SQLite file",
                    detail={"sidecars": [path.name for path in sidecars]},
                )
            with staging_path.open("rb") as stream:
                if stream.read(16) != b"SQLite format 3\x00":
                    raise BackupVerificationError("Invalid SQLite header")
            with closing(
                sqlite3.connect(
                    _readonly_uri(staging_path),
                    uri=True,
                    timeout=settings.sqlite_busy_timeout_ms / 1000,
                )
            ) as connection:
                integrity_rows = [row[0] for row in connection.execute("PRAGMA integrity_check")]
                if integrity_rows != ["ok"]:
                    raise BackupVerificationError(
                        "SQLite integrity check failed",
                        detail={"results": integrity_rows[:10]},
                    )

                foreign_key_violation = connection.execute("PRAGMA foreign_key_check").fetchone()
                if foreign_key_violation is not None:
                    raise BackupVerificationError(
                        "SQLite foreign-key check failed",
                        detail={"first_violation": list(foreign_key_violation)},
                    )

                revisions = [
                    row[0]
                    for row in connection.execute(
                        "SELECT version_num FROM alembic_version ORDER BY version_num"
                    )
                ]
        except BackupVerificationError:
            raise
        except sqlite3.Error as exc:
            raise BackupVerificationError("Cannot verify backup schema and integrity") from exc

        if revisions != [self.expected_revision]:
            raise SchemaRevisionMismatchError(
                "The database revision does not match the build's expected revision",
                detail={"expected": self.expected_revision, "found": revisions},
            )
        return revisions[0]

    @staticmethod
    def _write_manifest(path: Path, manifest: dict[str, Any]) -> None:
        with path.open("x", encoding="utf-8", newline="\n") as stream:
            json.dump(manifest, stream, ensure_ascii=False, indent=2, sort_keys=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())

    def _cleanup_stale_orphans(self) -> None:
        """Remove only uniquely named incomplete PFIM artifacts older than 24 hours. This grace
        period avoids interfering with backups in another process. Never delete legacy files,
        finished backups, or names that do not match exactly.
        """

        cutoff = dt.datetime.now(dt.UTC).timestamp() - _ORPHAN_GRACE_PERIOD.total_seconds()
        try:
            candidates = list(self.data_dir.iterdir())
        except OSError:
            return
        for path in candidates:
            remove = _ORPHAN_FILENAME_PATTERN.fullmatch(path.name) is not None
            if _FINAL_MANIFEST_PATTERN.fullmatch(path.name):
                database_name = path.name.removesuffix(".manifest.json") + ".db"
                remove = not (self.data_dir / database_name).exists()
            if not remove:
                continue
            try:
                if path.is_file() and path.stat().st_mtime < cutoff:
                    path.unlink()
            except FileNotFoundError:
                continue
            except OSError:
                # Cleanup must not turn a harmless orphan into a new-backup failure; retry it later.
                #
                continue

    def create_backup(self) -> BackupInfo:
        """Create, verify, and publish a consistent database snapshot."""

        self._ensure_backup_enabled()
        if not self.db_path.is_file():
            raise NotFoundError(
                "No existing database to back up",
                detail={"path": str(self.db_path)},
            )

        with operation_lock(self.data_dir).hold(
            timeout=float(settings.restore_quiesce_timeout_seconds)
        ):
            if (self.data_dir / ".pfim-restore.json").exists():
                raise BackupUnavailableError(
                    "Incomplete restore detected: backup suspended until recovery"
                )
            return self._create_backup_locked()

    def _create_backup_locked(self) -> BackupInfo:
        """Create a backup while the caller holds the operational lock. Restore uses this variant
        for its preliminary snapshot without reacquiring the interprocess lock.
        """

        self._ensure_backup_enabled()
        if not self.db_path.is_file():
            raise NotFoundError(
                "No existing database to back up",
                detail={"path": str(self.db_path)},
            )
        self._cleanup_stale_orphans()
        (
            final_database,
            final_manifest,
            staging_database,
            staging_manifest,
        ) = self._new_paths()
        manifest_published = False
        database_published = False
        try:
            self._online_copy(staging_database)
            revision = self._validate_staging(staging_database)
            digest = _sha256(staging_database)
            stat = staging_database.stat()
            created_at = dt.datetime.now(dt.UTC)
            manifest = {
                "format_version": _MANIFEST_FORMAT_VERSION,
                "database_filename": final_database.name,
                "size_bytes": stat.st_size,
                "sha256": digest,
                "created_at": created_at.isoformat(),
                "alembic_revision": revision,
                "integrity_check": "ok",
                "foreign_key_violations": 0,
            }
            self._write_manifest(staging_manifest, manifest)
            _fsync_file(staging_database)

            # The database is the commit marker: consumers cannot see the final filename before its
            # manifest exists.
            durable_replace(staging_manifest, final_manifest)
            manifest_published = True
            durable_replace(staging_database, final_database)
            database_published = True
            _fsync_directory(self.data_dir)

            restore_configuration_reason = self._restore_configuration_reason()
            return BackupInfo(
                filename=final_database.name,
                size_bytes=stat.st_size,
                created_at=created_at,
                verified=True,
                sha256=digest,
                alembic_revision=revision,
                manifest_filename=final_manifest.name,
                restore_eligible=restore_configuration_reason is None,
                restore_ineligible_reason=restore_configuration_reason,
            )
        finally:
            # Remove only unique staging names generated by this invocation. Never delete a published
            # final backup on a late error path.
            #
            staging_database.unlink(missing_ok=True)
            staging_manifest.unlink(missing_ok=True)
            for sidecar in _sqlite_sidecars(staging_database):
                sidecar.unlink(missing_ok=True)
            if manifest_published and not database_published:
                final_manifest.unlink(missing_ok=True)

    @staticmethod
    def _read_manifest(backup_path: Path) -> dict[str, Any] | None:
        """Shared restore interface: only verified manifests are accepted."""
        return BackupService._inspect_manifest(backup_path)[0]

    @staticmethod
    def _inspect_manifest(backup_path: Path) -> tuple[dict[str, Any] | None, str | None]:
        path = _manifest_path(backup_path)
        try:
            if (
                not backup_path.is_file()
                or backup_path.is_symlink()
                or backup_path.stat().st_nlink != 1
            ):
                return None, "manifest_invalid"
            if not path.exists() and not path.is_symlink():
                return None, "manifest_missing"
            if not path.is_file() or path.is_symlink() or path.stat().st_nlink != 1:
                return None, "manifest_invalid"
            before = backup_path.stat()
            payload = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(payload, dict):
                return None, "manifest_invalid"
            if (
                type(payload.get("format_version")) is not int
                or payload.get("format_version") != _MANIFEST_FORMAT_VERSION
                or payload.get("database_filename") != backup_path.name
                or type(payload.get("size_bytes")) is not int
                or payload.get("size_bytes", 0) <= 0
                or payload.get("size_bytes") != before.st_size
                or not isinstance(payload.get("sha256"), str)
                or re.fullmatch(r"[0-9a-f]{64}", payload["sha256"]) is None
                or not isinstance(payload.get("alembic_revision"), str)
                or not payload["alembic_revision"].strip()
                or payload.get("integrity_check") != "ok"
                or type(payload.get("foreign_key_violations")) is not int
                or payload.get("foreign_key_violations") != 0
                or not isinstance(payload.get("created_at"), str)
            ):
                return None, "manifest_invalid"
            created_at = dt.datetime.fromisoformat(payload["created_at"])
            if created_at.tzinfo is None or created_at.utcoffset() is None:
                return None, "manifest_invalid"
            # Canonicalize only in memory; never rewrite the file.
            payload["created_at"] = created_at.astimezone(dt.UTC).isoformat()
            if _sha256(backup_path) != payload["sha256"]:
                return None, "hash_mismatch"
            after = backup_path.stat()
            if (before.st_size, before.st_mtime_ns) != (after.st_size, after.st_mtime_ns):
                return None, "backup_changed"
        except (OSError, ValueError, TypeError, OverflowError, RecursionError):
            return None, "manifest_invalid"
        return payload, None

    def list_backups(self) -> list[BackupInfo]:
        backups: list[BackupInfo] = []
        if not self.data_dir.is_dir():
            return backups
        for path in self.data_dir.glob("pfim_backup_*.db"):
            if not is_valid_backup_filename(path.name):
                continue
            try:
                if not path.is_file():
                    continue
                stat = path.stat()
                manifest, verification_error = self._inspect_manifest(path)
                created_at = dt.datetime.fromtimestamp(stat.st_mtime, tz=dt.UTC)
                if manifest is not None:
                    created_at = dt.datetime.fromisoformat(manifest["created_at"])
            except (KeyError, OSError, TypeError, ValueError):
                continue
            restore_configuration_reason = self._restore_configuration_reason()
            has_sidecars = bool(_present_sqlite_sidecars(path))
            catalog_verified = manifest is not None and not has_sidecars
            backups.append(
                BackupInfo(
                    filename=path.name,
                    size_bytes=stat.st_size,
                    created_at=created_at,
                    verified=catalog_verified,
                    verification_error="sidecars_present" if has_sidecars else verification_error,
                    sha256=manifest.get("sha256") if catalog_verified else None,
                    alembic_revision=(
                        manifest.get("alembic_revision") if catalog_verified else None
                    ),
                    manifest_filename=(_manifest_path(path).name if catalog_verified else None),
                    restore_eligible=(
                        manifest is not None
                        and not has_sidecars
                        and manifest.get("alembic_revision") == self.expected_revision
                        and restore_configuration_reason is None
                    ),
                    restore_ineligible_reason=(
                        "sidecars_present"
                        if has_sidecars
                        else (
                            "not_verified"
                            if manifest is None
                            else (
                                "revision_mismatch"
                                if manifest.get("alembic_revision") != self.expected_revision
                                else restore_configuration_reason
                            )
                        )
                    ),
                )
            )
        return sorted(backups, key=lambda backup: backup.created_at, reverse=True)

    def get_backup_path(self, filename: str) -> Path:
        if not is_valid_backup_filename(filename):
            raise ValidationErrorPFIM(
                "Invalid backup filename",
                detail={"filename": filename},
            )
        path = self.data_dir / filename
        if not path.is_file():
            raise NotFoundError(f"Backup '{filename}' not found", detail={"filename": filename})
        try:
            if (
                path.is_symlink()
                or path.stat().st_nlink != 1
                or os.path.samefile(path, self.db_path)
            ):
                raise BackupVerificationError(
                    "The backup must be a file separate from the operational database",
                    detail={"filename": filename},
                )
        except FileNotFoundError as exc:
            raise NotFoundError(
                f"Backup '{filename}' not found", detail={"filename": filename}
            ) from exc
        sidecars = _present_sqlite_sidecars(path)
        if sidecars:
            raise BackupVerificationError(
                "The selected backup is not a self-contained SQLite file",
                detail={"filename": filename, "sidecars": [item.name for item in sidecars]},
            )
        manifest, verification_error = self._inspect_manifest(path)
        if manifest is None and (
            verification_error != "manifest_missing"
            or _NEW_BACKUP_FILENAME_PATTERN.fullmatch(filename)
        ):
            raise BackupVerificationError(
                "Invalid backup hash or manifest",
                detail={"filename": filename},
            )
        return path

    def get_manifest_path(self, filename: str) -> Path:
        backup_path = self.get_backup_path(filename)
        path = _manifest_path(backup_path)
        if not path.is_file():
            raise NotFoundError(
                "No verified manifest is available for this backup",
                detail={"filename": filename},
            )
        return path

    def restore_backup(
        self,
        filename: str,
        request: RestoreRequest,
        *,
        current_request_tracked: bool = True,
    ) -> RestoreResult:
        from app.services.restore_service import RestoreService

        return RestoreService(backup_service=self).restore_backup(
            filename,
            request,
            current_request_tracked=current_request_tracked,
        )
