"""Shared invariants for every persisted cash movement. Manual entry, CSV import, and movements
generated by trades, income, costs, and transfers all use the same rules, keeping preview and
writes consistent.
"""

from __future__ import annotations

from decimal import Decimal

from sqlalchemy.orm import Session

from app.models.category import Category
from app.repositories.category_repo import CategoryRepository
from app.utils.errors import ValidationErrorPFIM


class TransactionRules:
    """Validate the category and amount sign before constructing a Transaction."""

    def __init__(self, db: Session):
        self.category_repo = CategoryRepository(db)

    def validate_category(
        self,
        category_id: int | None,
        amount: Decimal,
        *,
        allow_transfer: bool = False,
        expected_type: str | None = None,
    ) -> Category:
        normalized_amount = Decimal(str(amount))
        if normalized_amount == 0:
            raise ValidationErrorPFIM(
                "The transaction amount cannot be zero",
                detail={"amount": str(normalized_amount)},
            )

        if category_id is None:
            raise ValidationErrorPFIM("A category is required")

        category = self.category_repo.get(category_id)
        if category is None:
            raise ValidationErrorPFIM(
                f"Category {category_id} not found",
                detail={"category_id": category_id},
            )

        if self.category_repo.has_children(category.id):
            raise ValidationErrorPFIM(
                "The assigned category must be a leaf with no subcategories",
                detail={"category_id": category.id},
            )

        if expected_type is not None and category.type != expected_type:
            raise ValidationErrorPFIM(
                f"Category '{category.name}' must be of type '{expected_type}'",
                detail={
                    "category_id": category.id,
                    "category_type": category.type,
                    "expected_type": expected_type,
                },
            )

        if category.type == "transfer":
            if not allow_transfer:
                raise ValidationErrorPFIM(
                    "Transfer categories can only be used by the "
                    "dedicated account transfer workflow",
                    detail={"category_id": category.id},
                )
            return category

        if category.type == "income" and normalized_amount <= 0:
            raise ValidationErrorPFIM(
                "An income category requires an amount greater than zero",
                detail={"category_id": category.id, "amount": str(normalized_amount)},
            )
        if category.type == "expense" and normalized_amount >= 0:
            raise ValidationErrorPFIM(
                "An expense category requires an amount less than zero",
                detail={"category_id": category.id, "amount": str(normalized_amount)},
            )
        if category.type not in {"income", "expense"}:
            raise ValidationErrorPFIM(
                f"Unsupported category type: '{category.type}'",
                detail={"category_id": category.id, "category_type": category.type},
            )

        return category
