"""Link transactions to trades and income events.

Revision ID: b4d8f1a6c2e7
Revises: a7c2e5f9b1d3
Create Date: 2026-07-24 12:00:00.000000

Adds trade_id and income_event_id to transactions (specification §5.2), linking cash
movements generated by security purchases, sales, coupons, and dividends to their source
so account balances reflect investment activity.

Uses batch mode because SQLite cannot add foreign key constraints to existing tables
directly. batch_alter_table recreates the table.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4d8f1a6c2e7"
down_revision = "a7c2e5f9b1d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.add_column(sa.Column("trade_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("income_event_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_transactions_trade_id", "trades", ["trade_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_transactions_income_event_id", "income_events", ["income_event_id"], ["id"]
        )


def downgrade() -> None:
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.drop_constraint("fk_transactions_income_event_id", type_="foreignkey")
        batch_op.drop_constraint("fk_transactions_trade_id", type_="foreignkey")
        batch_op.drop_column("income_event_id")
        batch_op.drop_column("trade_id")
