"""Explicit tax event origin and ownership.

Revision ID: d4e8f2a6c1b9
Revises: a9e5c7d2b4f1
Create Date: 2026-08-17 18:00:00.000000

Backfill is intentionally conservative. Each row starts as legacy_unknown and becomes
automatic_trade only if it uniquely matches the complete deterministic signature of the
previous synchronizer: sale, date, type, description, and consistent amounts.
Customized, duplicate, or otherwise ambiguous rows are neither corrected nor deleted.

Reject duplicate or broken links before touching the schema, since there is no safe way
to choose which relation to retain.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4e8f2a6c1b9"
down_revision = "a9e5c7d2b4f1"
branch_labels = None
depends_on = None

ORIGIN_CHECK = "ck_tax_events_origin"
SINGLE_SOURCE_CHECK = "ck_tax_events_single_related_source"
AUTOMATIC_SOURCE_CHECK = "ck_tax_events_automatic_trade_source"
AUTOMATIC_UNIQUE_INDEX = "uq_tax_events_automatic_trade"


def _count(connection: sa.Connection, query: str) -> int:
    return int(connection.scalar(sa.text(query)) or 0)


def _verify_existing_links() -> None:
    connection = op.get_bind()
    problems = {
        "dual trade/income link": _count(
            connection,
            "SELECT COUNT(*) FROM tax_events "
            "WHERE related_trade_id IS NOT NULL AND related_income_id IS NOT NULL",
        ),
        "linked trade does not exist": _count(
            connection,
            """
            SELECT COUNT(*)
            FROM tax_events AS te
            LEFT JOIN trades AS t ON t.id = te.related_trade_id
            WHERE te.related_trade_id IS NOT NULL AND t.id IS NULL
            """,
        ),
        "linked income event does not exist": _count(
            connection,
            """
            SELECT COUNT(*)
            FROM tax_events AS te
            LEFT JOIN income_events AS ie ON ie.id = te.related_income_id
            WHERE te.related_income_id IS NOT NULL AND ie.id IS NULL
            """,
        ),
    }
    found = {name: count for name, count in problems.items() if count}
    if found:
        details = ", ".join(f"{name}: {count}" for name, count in found.items())
        raise RuntimeError(
            "Tax event origin migration aborted: existing links require "
            f"an explicit decision ({details}). No backfill was performed."
        )


def upgrade() -> None:
    _verify_existing_links()

    with op.batch_alter_table("tax_events", recreate="always") as batch:
        batch.add_column(
            sa.Column(
                "origin",
                sa.String(length=30),
                nullable=False,
                server_default="manual",
            )
        )
        batch.create_check_constraint(
            ORIGIN_CHECK,
            "origin IN ('manual', 'automatic_trade', 'legacy_unknown')",
        )
        batch.create_check_constraint(
            SINGLE_SOURCE_CHECK,
            "related_trade_id IS NULL OR related_income_id IS NULL",
        )
        batch.create_check_constraint(
            AUTOMATIC_SOURCE_CHECK,
            "origin <> 'automatic_trade' OR "
            "(related_trade_id IS NOT NULL AND related_income_id IS NULL)",
        )
        batch.create_index(
            AUTOMATIC_UNIQUE_INDEX,
            ["related_trade_id"],
            unique=True,
            sqlite_where=sa.text("origin = 'automatic_trade'"),
        )

    connection = op.get_bind()
    connection.execute(sa.text("UPDATE tax_events SET origin = 'legacy_unknown'"))
    # Match the deterministic descriptions generated by the tax synchronizer.
    connection.execute(sa.text("""
            UPDATE tax_events
            SET origin = 'automatic_trade'
            WHERE id IN (
                SELECT MIN(te.id)
                FROM tax_events AS te
                JOIN trades AS t ON t.id = te.related_trade_id
                JOIN securities AS s ON s.id = t.security_id
                WHERE te.related_income_id IS NULL
                  AND t.type = 'sell'
                  AND te.event_date = t.date
                  AND (
                    (
                      te.event_type = 'capital_gain'
                      AND te.description = 'Capital gain realized on ' || s.ticker
                      AND te.gross_amount > 0
                      AND te.tax_rate IS NOT NULL
                      AND te.tax_amount IS NOT NULL
                      AND te.net_amount IS NOT NULL
                      AND ABS(te.tax_amount - (te.gross_amount * te.tax_rate / 100.0)) < 0.000001
                      AND ABS(te.net_amount - (te.gross_amount - te.tax_amount)) < 0.000001
                    )
                    OR
                    (
                      te.event_type = 'capital_loss'
                      AND te.description = 'Capital loss realized on ' || s.ticker
                      AND te.gross_amount < 0
                      AND te.tax_rate IS NULL
                      AND te.tax_amount IS NULL
                      AND te.net_amount IS NOT NULL
                      AND ABS(te.net_amount - te.gross_amount) < 0.000001
                    )
                  )
                GROUP BY te.related_trade_id
                HAVING COUNT(*) = 1
            )
            """))


def downgrade() -> None:
    with op.batch_alter_table("tax_events", recreate="always") as batch:
        batch.drop_index(AUTOMATIC_UNIQUE_INDEX)
        batch.drop_constraint(AUTOMATIC_SOURCE_CHECK, type_="check")
        batch.drop_constraint(SINGLE_SOURCE_CHECK, type_="check")
        batch.drop_constraint(ORIGIN_CHECK, type_="check")
        batch.drop_column("origin")
