import type { TaxEvent } from "@/api/tax";

export type TaxEventIdentity = Pick<TaxEvent, "origin" | "related_trade_id" | "related_income_id">;

/** Links describe a source, never ownership of a tax entry. */
export function describeTaxEvent(event: TaxEventIdentity) {
  const linked = event.related_trade_id !== null || event.related_income_id !== null;
  switch (event.origin) {
    case "automatic_trade":
      return { label: "Automatically generated by trade", editable: false, canUnlink: false, sourceManaged: true };
    case "manual":
      return { label: "Manual", editable: true, canUnlink: linked, sourceManaged: false };
    case "legacy_unknown":
      return { label: "Origin requires verification", editable: true, canUnlink: linked, sourceManaged: false };
    default:
      return { label: "Unrecognised origin", editable: false, canUnlink: false, sourceManaged: false };
  }
}
